# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU/Pipelined_CPU.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU/Pipelined_CPU.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU/Pipelined_CPU.srcs/sources_1/ip/ROM/ROM.xci
# IP: The module: 'ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU/Pipelined_CPU.gen/sources_1/ip/ROM/ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
