# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.gen/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.srcs/sources_1/ip/Memory/Memory.xci
# IP: The module: 'Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.gen/sources_1/ip/Memory/Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
