# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test_clk.xdc

# Block Designs: bd/DDR3_AXI4/DDR3_AXI4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3_AXI4 || ORIG_REF_NAME==DDR3_AXI4} -quiet] -quiet

# IP: bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3_AXI4_processing_system7_0_0 || ORIG_REF_NAME==DDR3_AXI4_processing_system7_0_0} -quiet] -quiet

# IP: bd/DDR3_AXI4/ip/DDR3_AXI4_auto_pc_0/DDR3_AXI4_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3_AXI4_auto_pc_0 || ORIG_REF_NAME==DDR3_AXI4_auto_pc_0} -quiet] -quiet

# IP: bd/DDR3_AXI4/ip/DDR3_AXI4_axi_interconnect_0_0/DDR3_AXI4_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3_AXI4_axi_interconnect_0_0 || ORIG_REF_NAME==DDR3_AXI4_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/DDR3_AXI4/ip/DDR3_AXI4_proc_sys_reset_0_0/DDR3_AXI4_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR3_AXI4_proc_sys_reset_0_0 || ORIG_REF_NAME==DDR3_AXI4_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.gen/sources_1/bd/DDR3_AXI4/DDR3_AXI4_ooc.xdc
