# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.srcs/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xci
# IP: The module: 'DDR3_AXI4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.srcs/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xci
# IP: The module: 'DDR3_AXI4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU_With_Cache/Pipelined_CPU_With_Cache.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
