# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0.xci
# IP: The module: 'DDR3_AXI4_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0.xci
# IP: The module: 'DDR3_AXI4_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR3_AXI4_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
