# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.runs/synth_1/SoC_Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.statsThreshold 360
set_param chipscope.maxJobs 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.cache/wt} [current_project]
set_property parent.project_path {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{C:/Users/11545/Desktop/Zynq CPU/Single_Period_CPU/Control_Logic_ROM_Init.coe}}
add_files {{C:/Users/11545/Desktop/Zynq CPU/Pipelined_CPU/Pipelined_CPU_Test_IMEM.coe}}
read_verilog -library xil_defaultlib {
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/ALU.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/AXI_Arbiter.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Branch_Comp.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Branch_Taken_Delay.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Control_Logic.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/D_Cache.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Forwarding_Unit.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Hazard_Detection_Unit.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/I_Cache.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Imm_gen.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Instruction_Buffer.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/PC.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Pipe_Reg.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/RegFile.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Register.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Single_Period_CPU.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/partial_load.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/partial_store.v}
  {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/new/Soc_Top.v}
}
add_files {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/bd/DDR3_AXI4/DDR3_AXI4.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_processing_system7_0_0/DDR3_AXI4_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_proc_sys_reset_0_0/DDR3_AXI4_proc_sys_reset_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_proc_sys_reset_0_0/DDR3_AXI4_proc_sys_reset_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_proc_sys_reset_0_0/DDR3_AXI4_proc_sys_reset_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_axi_gpio_0_0/DDR3_AXI4_axi_gpio_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_rst_ps7_0_50M_1/DDR3_AXI4_rst_ps7_0_50M_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_rst_ps7_0_50M_1/DDR3_AXI4_rst_ps7_0_50M_1.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_rst_ps7_0_50M_1/DDR3_AXI4_rst_ps7_0_50M_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_auto_pc_0/DDR3_AXI4_auto_pc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/ip/DDR3_AXI4_auto_pc_1/DDR3_AXI4_auto_pc_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/bd/DDR3_AXI4/DDR3_AXI4_ooc.xdc}}]

read_ip -quiet {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/ip/Data_Array/Data_Array.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/ip/Data_Array/Data_Array_ooc.xdc}}]

read_ip -quiet {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/ip/Tag_Array/Tag_Array.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/ip/Tag_Array/Tag_Array_ooc.xdc}}]

read_ip -quiet {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/sources_1/ip/I_Tag_Array/I_Tag_Array.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.gen/sources_1/ip/I_Tag_Array/I_Tag_Array_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/constrs_1/new/test_clk.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/constrs_1/new/test_clk.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {C:/Users/11545/Desktop/Zynq CPU/CPU_With_OS/CPU_With_OS.srcs/utils_1/imports/synth_1/Pipelined_CPU.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top SoC_Top -part xc7z020clg400-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SoC_Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file SoC_Top_utilization_synth.rpt -pb SoC_Top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
